export const primeVueButtonSemantic = {
  button: {
    background: '{primary.500}',
    borderColor: '{primary.500}',
    color: '{monochrome.white}',
    hoverBackground: '{primary.600}',
    hoverBorderColor: '{primary.600}',
    hoverColor: '{monochrome.white}',
    activeBackground: '{primary.700}',
    activeBorderColor: '{primary.700}',
    activeColor: '{monochrome.white}',
    padding: '0.625rem 1.25rem',
  },
  secondaryButton: {
    background: '{surface.700}',
    borderColor: '{surface.700}',
    color: '{monochrome.white}',
    hoverBackground: '{surface.800}',
    hoverBorderColor: '{surface.800}',
    hoverColor: '{monochrome.white}',
    activeBackground: '{surface.900}',
    activeBorderColor: '{surface.900}',
    activeColor: '{monochrome.white}',
  },
  successButton: {
    background: '{primary.500}',
    borderColor: '{primary.500}',
    color: '{monochrome.white}',
    hoverBackground: '{primary.600}',
    hoverBorderColor: '{primary.600}',
    hoverColor: '{monochrome.white}',
    activeBackground: '{primary.700}',
    activeBorderColor: '{primary.700}',
    activeColor: '{monochrome.white}',
  },
  dangerButton: {
    background: '{red.500}',
    borderColor: '{red.500}',
    color: '{monochrome.white}',
    hoverBackground: '{red.600}',
    hoverBorderColor: '{red.600}',
    hoverColor: '{monochrome.white}',
    activeBackground: '{red.500}',
    activeBorderColor: '{red.500}',
    activeColor: '{monochrome.white}',
  },
  warningButton: {
    background: '{orange.500}',
    borderColor: '{orange.500}',
    color: '{monochrome.black}',
    hoverBackground: '{orange.600}',
    hoverBorderColor: '{orange.600}',
    hoverColor: '{monochrome.black}',
    activeBackground: '{orange.500}',
    activeBorderColor: '{orange.500}',
    activeColor: '{monochrome.black}',
  },
  infoButton: {
    background: '{blue.500}',
    borderColor: '{blue.500}',
    color: '{monochrome.white}',
    hoverBackground: '{blue.600}',
    hoverBorderColor: '{blue.600}',
    hoverColor: '{monochrome.white}',
    activeBackground: '{blue.500}',
    activeBorderColor: '{blue.500}',
    activeColor: '{monochrome.white}',
  },
} as const
