export const primeVueFeedbackSemantic = {
  toast: {
    background: '{surface.0}',
    borderColor: '{surface.200}',
    color: '{surface.900}',
    successBackground: '{green.100}',
    successBorderColor: '{green.300}',
    successColor: '{green.900}',
    infoBackground: '{blue.100}',
    infoBorderColor: '{blue.300}',
    infoColor: '{blue.900}',
    warningBackground: '{orange.100}',
    warningBorderColor: '{orange.300}',
    warningColor: '{orange.900}',
    errorBackground: '{red.100}',
    errorBorderColor: '{red.300}',
    errorColor: '{red.900}',
  },
  message: {
    background: '{surface.0}',
    borderColor: '{surface.200}',
    color: '{surface.900}',
    successBackground: '{green.100}',
    successBorderColor: '{green.300}',
    successColor: '{green.900}',
    infoBackground: '{blue.100}',
    infoBorderColor: '{blue.300}',
    infoColor: '{blue.900}',
    warningBackground: '{orange.100}',
    warningBorderColor: '{orange.300}',
    warningColor: '{orange.900}',
    errorBackground: '{red.100}',
    errorBorderColor: '{red.300}',
    errorColor: '{red.900}',
  },
} as const
