export const primeVueFormSemantic = {
  input: {
    background: '{surface.0}',
    borderColor: '{surface.300}',
    color: '{surface.900}',
    hoverBorderColor: '{primary.400}',
    focusBorderColor: '{primary.900}',
    invalidBorderColor: '{red.500}',
    placeholderColor: '{surface.500}',
    disabledBackground: '{surface.100}',
    disabledBorderColor: '{surface.400}',
    disabledColor: '{surface.500}',
  },
  dropdown: {
    background: '{surface.0}',
    borderColor: '{surface.300}',
    color: '{surface.900}',
    hoverBorderColor: '{primary.400}',
    focusBorderColor: '{primary.900}',
    itemHoverBackground: '{surface.100}',
    itemFocusBackground: '{surface.100}',
    panelBackground: '{surface.0}',
    panelBorderColor: '{surface.200}',
    panelColor: '{surface.900}',
  },
  checkbox: {
    background: '{surface.0}',
    checkedBackground: '{primary.900}',
    checkedHoverBackground: '{primary.800}',
    borderColor: '{surface.300}',
    hoverBorderColor: '{primary.400}',
    focusBorderColor: '{primary.900}',
    checkedBorderColor: '{primary.900}',
    checkedHoverBorderColor: '{primary.800}',
    iconColor: '{monochrome.white}',
  },
  toggle: {
    sliderBackground: '{surface.300}',
    sliderHoverBackground: '{surface.400}',
    checkedSliderBackground: '{primary.900}',
    checkedSliderHoverBackground: '{primary.800}',
    handleBackground: '{surface.0}',
    checkedHandleBackground: '{surface.0}',
  },
} as const
