export const primeVueNavigationSemantic = {
  panel: {
    background: '{surface.100}',
    borderColor: '{surface.200}',
    color: '{surface.900}',
    headerBackground: '{surface.100}',
    headerColor: '{surface.900}',
  },
  accordion: {
    background: '{surface.100}',
    borderColor: '{surface.200}',
    color: '{surface.900}',
    headerBackground: '{surface.100}',
    headerColor: '{surface.900}',
    hoverHeaderBackground: '{surface.200}',
    hoverHeaderColor: '{surface.900}',
    activeHeaderBackground: '{surface.200}',
    activeHeaderColor: '{primary.900}',
  },
  tabview: {
    background: '{surface.100}',
    borderColor: '{surface.200}',
    color: '{surface.900}',
    tabBackground: '{surface.100}',
    tabColor: '{surface.700}',
    tabHoverBackground: '{surface.200}',
    tabHoverColor: '{surface.900}',
    activeTabBackground: '{surface.100}',
    activeTabColor: '{primary.900}',
  },
  menu: {
    background: '{surface.100}',
    borderColor: '{surface.200}',
    color: '{surface.900}',
    itemBackground: '{surface.100}',
    itemColor: '{surface.700}',
    itemHoverBackground: '{surface.200}',
    itemHoverColor: '{surface.900}',
    itemActiveBackground: '{surface.200}',
    itemActiveColor: '{primary.900}',
  },
  stepper: {
    background: '{surface.100}',
    borderColor: '{surface.200}',
    color: '{surface.900}',
    stepBackground: '{surface.100}',
    stepColor: '{surface.700}',
    activeStepBackground: '{surface.100}',
    activeStepColor: '{primary.900}',
  },
} as const
