export const primeVueDataDisplaySemantic = {
  table: {
    background: '{surface.100}',
    borderColor: '{surface.200}',
    color: '{surface.900}',
    headerBackground: '{surface.100}',
    headerColor: '{surface.900}',
    rowBackground: '{surface.100}',
    rowColor: '{surface.900}',
    evenRowBackground: '{surface.100}',
    evenRowColor: '{surface.900}',
    hoverRowBackground: '{surface.200}',
    hoverRowColor: '{surface.900}',
  },
  list: {
    background: '{surface.100}',
    borderColor: '{surface.200}',
    color: '{surface.900}',
    optionBackground: '{surface.100}',
    optionColor: '{surface.900}',
    optionHoverBackground: '{surface.200}',
    optionHoverColor: '{surface.900}',
    optionSelectedBackground: '{surface.200}',
    optionSelectedColor: '{primary.900}',
  },
  tag: {
    primaryBackground: '{primary.100}',
    primaryColor: '{primary.900}',
    successBackground: '{primary.100}',
    successColor: '{primary.900}',
    infoBackground: '{blue.100}',
    infoColor: '{blue.800}',
    warningBackground: '{orange.100}',
    warningColor: '{orange.800}',
    dangerBackground: '{red.100}',
    dangerColor: '{red.800}',
  },
  badge: {
    primaryBackground: '{primary.900}',
    primaryColor: '{monochrome.white}',
    successBackground: '{primary.500}',
    successColor: '{monochrome.white}',
    infoBackground: '{blue.500}',
    infoColor: '{monochrome.black}',
    warningBackground: '{orange.500}',
    warningColor: '{monochrome.black}',
    dangerBackground: '{red.500}',
    dangerColor: '{monochrome.white}',
  },
  progressbar: {
    background: '{surface.200}',
    primaryColor: '{primary.900}',
    successColor: '{primary.500}',
    infoColor: '{blue.500}',
    warningColor: '{orange.500}',
    dangerColor: '{red.500}',
  },
} as const
