<template>
  <Dialog
    :visible="visible"
    modal
    :breakpoints="{ '1199px': '60vw', '575px': '92vw' }"
    :style="{ width: '34rem' }"
    :header="t('create.title')"
    :closable="!saving"
    @update:visible="onVisibleChange"
  >
    <div class="create-document-form">
      <div class="form-group">
        <label for="cd-type" class="form-label">{{ t('create.type_label') }}</label>
        <SelectButton
          id="cd-type"
          v-model="type"
          :options="typeOptions"
          option-label="label"
          option-value="value"
          :allow-empty="false"
          :aria-label="t('create.type_label')"
        />
        <small class="form-help">
          {{ type === 'docx' ? t('create.type_hint_docx') : t('create.type_hint_html') }}
        </small>
      </div>

      <!-- HTML-КП can be generated by the AI: skip the manual form entirely. -->
      <div v-if="type === 'html'" class="create-ai-cta">
        <Button
          :label="t('create.ai_generate')"
          icon="pi pi-sparkles"
          severity="help"
          outlined
          class="w-full"
          :disabled="saving"
          @click="openAiGeneration"
        />
        <small class="form-help">{{ t('create.ai_generate_hint') }}</small>
      </div>

      <div class="form-group">
        <label for="cd-name-ru" class="form-label">
          {{ t('create.name_ru_label') }} <span class="required">*</span>
        </label>
        <InputText
          id="cd-name-ru"
          v-model="nameRu"
          class="w-full"
          :placeholder="t('create.name_ru_placeholder')"
          :class="{ 'p-invalid': errors.nameRu }"
          @input="errors.nameRu = ''"
        />
        <small v-if="errors.nameRu" class="p-error">{{ errors.nameRu }}</small>
      </div>

      <div class="form-group">
        <label for="cd-name-en" class="form-label">{{ t('create.name_en_label') }}</label>
        <InputText
          id="cd-name-en"
          v-model="nameEn"
          class="w-full"
          :placeholder="t('create.name_en_placeholder')"
        />
      </div>

      <div class="form-group">
        <label for="cd-desc-ru" class="form-label">{{ t('create.description_ru_label') }}</label>
        <Textarea
          id="cd-desc-ru"
          v-model="descriptionRu"
          class="w-full"
          rows="2"
          auto-resize
          :placeholder="t('create.description_ru_placeholder')"
        />
      </div>

      <div class="form-group">
        <label for="cd-desc-en" class="form-label">{{ t('create.description_en_label') }}</label>
        <Textarea
          id="cd-desc-en"
          v-model="descriptionEn"
          class="w-full"
          rows="2"
          auto-resize
          :placeholder="t('create.description_en_placeholder')"
        />
      </div>
    </div>

    <template #footer>
      <Button :label="t('create.cancel')" text @click="close" :disabled="saving" />
      <Button :label="t('create.submit')" :loading="saving" @click="submit" />
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import { reactive, ref, watch } from 'vue'
import Dialog from 'primevue/dialog'
import InputText from 'primevue/inputtext'
import Textarea from 'primevue/textarea'
import SelectButton from 'primevue/selectbutton'
import Button from 'primevue/button'
import { useServices } from '@/services'
import { useNotifications } from '@/composables/useNotifications'
import { useLocalI18n } from '@/composables/useLocalI18n'
import { useDocumentGenerationModalStore } from '@/stores/documentGenerationModal'
import type { DocumentTemplateType } from '@/entities/document'
import type { CreateDocumentTemplateRequest } from '@/api/types/documents'
import en from '../locale/en.json'
import ru from '../locale/ru.json'

const props = defineProps<{ visible: boolean }>()
const emit = defineEmits<{
  (e: 'update:visible', value: boolean): void
  (e: 'created', id: number): void
}>()

const { t } = useLocalI18n({ en, ru })
const { documentService } = useServices()
const { notifySuccess, notifyApiError } = useNotifications()
const documentGenerationModal = useDocumentGenerationModalStore()

const typeOptions: { label: string; value: DocumentTemplateType }[] = [
  { label: t('create.type_docx'), value: 'docx' },
  { label: t('create.type_html'), value: 'html' },
]

// docx is the primary scenario for the manual Word flow, so it leads.
const type = ref<DocumentTemplateType>('docx')
const nameRu = ref('')
const nameEn = ref('')
const descriptionRu = ref('')
const descriptionEn = ref('')
const saving = ref(false)
const errors = reactive<{ nameRu: string }>({ nameRu: '' })

const reset = () => {
  type.value = 'docx'
  nameRu.value = ''
  nameEn.value = ''
  descriptionRu.value = ''
  descriptionEn.value = ''
  errors.nameRu = ''
  saving.value = false
}

// Re-seed a clean form every time the dialog re-opens.
watch(
  () => props.visible,
  (visible) => {
    if (visible) reset()
  },
)

const onVisibleChange = (value: boolean) => {
  if (!value && saving.value) return
  emit('update:visible', value)
}

const close = () => {
  emit('update:visible', false)
}

/**
 * HTML-КП "generate via AI" — close the manual create dialog and pop the
 * document-generation modal. The chat (and the template) are created lazily on
 * the first send inside the modal; manual create stays for docx (uploaded
 * Word templates can't be AI-generated).
 */
const openAiGeneration = () => {
  close()
  documentGenerationModal.open()
}

const submit = async () => {
  const ruName = nameRu.value.trim()
  if (!ruName) {
    errors.nameRu = t('create.name_required')
    return
  }

  const name: Record<string, string> = { ru: ruName }
  const enName = nameEn.value.trim()
  if (enName) name.en = enName

  let description: Record<string, string> | null = null
  const ruDesc = descriptionRu.value.trim()
  const enDesc = descriptionEn.value.trim()
  if (ruDesc || enDesc) {
    description = {}
    if (ruDesc) description.ru = ruDesc
    if (enDesc) description.en = enDesc
  }

  const payload: CreateDocumentTemplateRequest = {
    name,
    description,
    type: type.value,
    config: {},
  }

  saving.value = true
  try {
    const created = await documentService.createTemplate(payload)
    notifySuccess(t('create.success'))
    emit('created', created.id)
  } catch (error: unknown) {
    notifyApiError(error, t('create.error'))
  } finally {
    saving.value = false
  }
}
</script>

<style lang="scss" scoped>
.create-document-form {
  display: flex;
  flex-direction: column;
  gap: 1rem;

  .create-ai-cta {
    display: flex;
    flex-direction: column;
    gap: 0.4rem;
    padding: 0.75rem;
    border: 1px dashed rgba($primary, 0.4);
    border-radius: $card-border-radius;
    background: rgba($primary, 0.03);
  }

  .form-group {
    display: flex;
    flex-direction: column;
    gap: 0.4rem;

    .form-label {
      font-size: $font-size-sm;
      font-weight: $font-weight-medium;
      color: $surface-700;

      .required {
        color: $danger;
      }
    }

    .form-help {
      font-size: $font-size-xs;
      color: $surface-500;
    }

    .p-error {
      color: $danger;
      font-size: $font-size-xs;
    }
  }
}
</style>
